In [6]:
import pandas as pd

# Loading the data 
url = 'https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A23d42528-1048-45d4-85d1-7e13b666e744'
prey = pd.read_csv(url)
pd.set_option("display.max_columns", None)
prey

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [7]:
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

In [8]:
prey.tail()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [9]:
prey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111156 entries, 0 to 111155
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   class                          111156 non-null  object
 1   order                          111054 non-null  object
 2   family                         111156 non-null  object
 3   genus                          111156 non-null  object
 4   species                        111156 non-null  object
 5   lat                            111156 non-null  float64
 6   long                           111156 non-null  float64
 7   eventDate                      111156 non-null  object
 8   day                            110998 non-null  float64
 9   month                          111127 non-null  float64
 10  year                           111156 non-null  int64
 11  institutionCode                110414 non-null  object
 12  coordinateUncertaintyInMeters  84686 non-null   float64
 13  basisOfRecord                  111156 non-null  object
 14  individualCount                6351 non-null    float64
 15  datasetKey                     111156 non-null  object
 16  ID                             111156 non-null  int64
 17  bio1                           109629 non-null  float64
 18  bio10                          109629 non-null  float64
 19  bio11                          109629 non-null  float64
 20  bio12                          109629 non-null  float64
 21  bio13                          109629 non-null  float64
 22  bio14                          109629 non-null  float64
 23  bio15                          109629 non-null  float64
 24  bio16                          109629 non-null  float64
 25  bio17                          109629 non-null  float64
 26  bio18                          109629 non-null  float64
 27  bio19                          109629 non-null  float64
 28  bio2                           109629 non-null  float64
 29  bio3                           109629 non-null  float64
 30  bio4                           109629 non-null  float64
 31  bio5                           109629 non-null  float64
 32  bio6                           109629 non-null  float64
 33  bio7                           109629 non-null  float64
 34  bio8                           109629 non-null  float64
 35  bio9                           109629 non-null  float64
 36  dist                           109500 non-null  float64
 37  dem90_hf                       107765 non-null  float64
 38  lc_class                       106905 non-null  object
 39  ndvi                           109663 non-null  float64
dtypes: float64(28), int64(2), object(10)
memory usage: 33.9+ MB

In [10]:
prey.nunique()

class                                 4
order                                18
family                               63
genus                                92
species                              97
lat                               91909
long                              91965
eventDate                        102140
day                                  31
month                                12
year                                 77
institutionCode                      77
coordinateUncertaintyInMeters      4450
basisOfRecord                         4
individualCount                      42
datasetKey                           88
ID                               111156
bio1                              11778
bio10                             11981
bio11                             11803
bio12                             12117
bio13                             12020
bio14                              4586
bio15                             11848
bio16                             12102
bio17                              9243
bio18                             10698
bio19                             12095
bio2                              11915
bio3                               8723
bio4                              12110
bio5                              11992
bio6                              11934
bio7                              12088
bio8                              11889
bio9                              11980
dist                              11718
dem90_hf                          11904
lc_class                             12
ndvi                              29093
dtype: int64

In [11]:
prey.rename(columns = {'institutionCode' : 'institution_code', 'datasetKey' : 'dataset_key'})

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [14]:
prey_updated = prey[(prey['basisOfRecord'] == 'PRESERVED_SPECIMEN') & (prey['year'].between(1992, 2000)) & (prey['lat'] >37) & (prey['long']<39)] 
prey_updated

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
1732,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,38.826049,-120.108584,1998-10-11T00:00:00Z,11.0,10.0,1998,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1733,47.266640,129.389542,-21.191164,1109.233276,189.963196,13.407290,70.784904,524.399963,57.491680,63.041679,515.479981,133.981216,43.549999,6100.312500,222.205154,-82.314064,304.519226,-10.491679,127.882248,2.310431,2385.305176,savanna,2616.363525
1741,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,37.522500,-118.206944,2000-07-23T00:00:00Z,23.0,7.0,2000,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1742,7.090353,86.143593,-56.522018,499.158325,74.596466,18.393005,44.046761,198.922470,68.051323,81.099709,193.088593,124.665611,43.000000,5818.619629,174.778275,-114.206703,288.984985,-54.073639,57.221279,22.681726,3328.460693,grassland,1301.136597
1744,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,38.841897,-120.089572,1999-09-05T00:00:00Z,5.0,9.0,1999,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1745,44.354473,126.458023,-23.423639,1107.232422,188.160217,13.882200,69.850784,520.618835,59.914043,64.953728,511.949371,132.853805,43.235706,6090.529297,218.140472,-84.527191,302.667664,-12.924361,125.083778,4.120187,2434.155029,savanna,2542.786133
1746,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,38.696450,-119.998880,2000-09-04T00:00:00Z,4.0,9.0,2000,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1747,35.024010,116.275528,-30.674471,1146.673096,191.761307,15.523396,68.833611,535.531555,64.432434,69.561111,505.288910,128.733948,43.000000,5997.387695,203.454208,-91.975990,295.430206,-19.581268,114.275528,8.972960,2595.387695,savanna,2743.423584
1752,Insecta,Orthoptera,Acrididae,Melanoplus,Melanoplus sanguinipes,39.104167,-119.908333,1998-10-21T00:00:00Z,21.0,10.0,1998,CSU,2000.0,PRESERVED_SPECIMEN,1.0,323b0e80-5e4b-4cc4-936a-d93fc8cae9bc,1753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109841,Insecta,Odonata,Aeshnidae,Anax,Anax junius,37.072629,-121.999822,1992-09-07T00:00:00Z,7.0,9.0,1992,UCSC,489.0,PRESERVED_SPECIMEN,NaN,db47a906-257f-40a8-8638-4cb1bf092c2b,109842,137.550003,183.692307,93.724098,818.934753,177.230591,2.000000,90.707207,452.680023,8.885489,14.335489,452.680023,130.070984,56.955318,3548.672363,259.344116,32.609589,226.734528,93.724098,180.457459,2.386282,241.694473,evergreen_broadleaf,7297.632324
109842,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.145907,-122.197842,1995-08-14T00:00:00Z,14.0,8.0,1995,UCSC,359.0,PRESERVED_SPECIMEN,NaN,db47a906-257f-40a8-8638-4cb1bf092c2b,109843,126.737839,173.159210,88.738449,941.762817,191.016846,2.926305,87.162216,499.676727,13.354136,17.767122,499.676727,118.593689,56.408169,3412.216797,243.195557,33.784195,209.411377,88.738449,168.232910,2.208592,533.248230,evergreen_needleleaf,8067.994141
109843,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.003284,-121.952227,1993-05-14T00:00:00Z,14.0,5.0,1993,UCSC,263.0,PRESERVED_SPECIMEN,NaN,db47a906-257f-40a8-8638-4cb1bf092c2b,109844,139.000000,179.196747,98.627991,697.140503,152.373886,2.000000,91.432846,388.278595,7.454078,12.450000,388.278595,126.835083,59.554077,3166.567627,248.737396,36.993736,211.743668,98.627991,175.196747,7.433326,84.384911,evergreen_needleleaf,6020.397949
109844,Insecta,Odonata,Coenagrionidae,Ischnura,Ischnura cervula,37.072629,-121.999822,1993-05-21T00:00:00Z,21.0,5.0,1993,UCSC,489.0,PRESERVED_SPECIMEN,NaN,db47a906-257f-40a8-8638-4cb1bf092c2b,109845,137.550003,183.692307,93.724098,818.934753,177.230591,2.000000,90.707207,452.680023,8.885489,14.335489,452.680023,130.070984,56.955318,3548.672363,259.344116,32.609589,226.734528,93.724098,180.457459,2.386282,241.694473,evergreen_broadleaf,7297.632324
109845,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,37.069317,-122.053877,1998-09-28T00:00:00Z,28.0,9.0,1998,UCSC,326.0,PRESERVED_SPECIMEN,NaN,db47a906-257f-40a8-8638-4cb1bf092c2b,109846,137.906937,180.938828,95.896576,787.717041,171.916595,2.000000,91.050003,438.944275,9.000000,14.000000,438.944275,127.601311,58.049999,3343.809082,253.102615,34.946579,218.156052,95.896576,177.479782,2.104761,180.299408,evergreen_needleleaf,6327.691895